import Script from "next/script";

export const metadata = {
  title: "Let's Manage",
  description: "Generated by Orion Development",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />

        <link rel="stylesheet" href="/assets/css/bootstrap.css" />

        <link
          rel="stylesheet"
          href="/assets/vendors/sweetalert2/sweetalert2.min.css"
        />

        <link
          rel="stylesheet"
          href="/assets/vendors/perfect-scrollbar/perfect-scrollbar.css"
        />
        <link
          rel="stylesheet"
          href="/assets/vendors/bootstrap-icons/bootstrap-icons.css"
        />
        <link rel="stylesheet" href="assets/css/app.css" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="/assets/css/bootstrap.css" />
        <link
          rel="stylesheet"
          href="/assets/vendors/bootstrap-icons/bootstrap-icons.css"
        />
        <link rel="stylesheet" href="/assets/css/app.css" />
        <link rel="stylesheet" href="/assets/css/pages/auth.css" />
      </head>
      <body>
        {children}

        <Script
          src="/assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/js/bootstrap.bundle.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="/assets/vendors/sweetalert2/sweetalert2.all.min.js"
          strategy="beforeInteractive"
        />

        <Script src="/assets/js/main.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
